// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// AccrualService is an autogenerated mock type for the AccrualService type
type AccrualService struct {
	mock.Mock
}

// Poller provides a mock function with given fields: ctx
func (_m *AccrualService) Poller(ctx context.Context) func() {
	ret := _m.Called(ctx)

	var r0 func()
	if rf, ok := ret.Get(0).(func(context.Context) func()); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(func())
		}
	}

	return r0
}
