// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/djokcik/gophermart/internal/model"
	mock "github.com/stretchr/testify/mock"

	provider "github.com/djokcik/gophermart/provider"
)

// AccrualClient is an autogenerated mock type for the AccrualClient type
type AccrualClient struct {
	mock.Mock
}

// GetOrder provides a mock function with given fields: ctx, orderID
func (_m *AccrualClient) GetOrder(ctx context.Context, orderID model.OrderID) (provider.AccrualResponse, error) {
	ret := _m.Called(ctx, orderID)

	var r0 provider.AccrualResponse
	if rf, ok := ret.Get(0).(func(context.Context, model.OrderID) provider.AccrualResponse); ok {
		r0 = rf(ctx, orderID)
	} else {
		r0 = ret.Get(0).(provider.AccrualResponse)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, model.OrderID) error); ok {
		r1 = rf(ctx, orderID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
